
Table "SIAMCHAI_STOCK"."SELL" {
  "ID" NUMBER [not null, default: '']
  "SELL_DATE" DATE [not null]
  "SELL_STAFF" NUMBER [not null]
  "SHOP_ID" NUMBER [not null]
  "COMPANY_ID" NUMBER [not null]
  "REMARK" "VARCHAR2(500 BYTE)"
  "STATUS" "VARCHAR2(20 BYTE)" [default: 'PASS']
  "CASH" NUMBER [default: 0]
  "CR_CARD" NUMBER [default: 0]
  "BANK_CHARGE" NUMBER
  "CLIENT_CHARGE" NUMBER
  "CREDIT_CARD_ID" NUMBER
  "TRANFER" NUMBER
  "CARD_NO" "VARCHAR2(100 BYTE)"
  "NET_PRICE_CHARGE" NUMBER
  "CREDIT_CARD_NAME" "VARCHAR2(255 BYTE)"
  "RECEIPT_NO" "VARCHAR2(20 BYTE)"
  "FREQUENCY" NUMBER
  "SALES_STAFF_ID" NUMBER
  "FINANCE_STAFF_ID" NUMBER
  "RECEIVE_CRCARD_DATE" DATE
  "CONTRACT_REF" "VARCHAR2(50 BYTE)"
  "PO_COST" NUMBER(10,2)
  "RECOMMENDED_PRICE" NUMBER(10,2)
  "RECEIVE_TRANSFER_DATE" DATE
  "CHECK_STATUS_DATE" DATE
  "DEBIT_RETURN" "CHAR(1 BYTE)"
  "BALANCE" NUMBER(10,2)
  "CONTRACT_ID" NUMBER [not null, default: 0]
  "MYSQL_CONTRACT_CODE" "VARCHAR2(50 BYTE)"
  "SYSTEM_DATE" DATE
  "SELL_TYPE" "CHAR(50 BYTE)" [not null, default: 'NORMAL']
  "SELL_ON_CASH" "CHAR(1 BYTE)"
  "PRODUCT_NAME" "VARCHAR2(255 BYTE)"
  "DUMMY_SERIAL" "VARCHAR2(255 BYTE)"
  "DUMMY_BARCODE" "VARCHAR2(255 BYTE)"
  "TOTAL_AMOUNT" NUMBER
  "VOID" "CHAR(1 BYTE)" [default: 'N']
  "SUM_VAT" NUMBER
  "SUM_COST" NUMBER
  "SUM_PO_COST" NUMBER
  "SUM_QTY" NUMBER
  "VOID_STAFF_ID" NUMBER
  "VOID_DATE" DATE
  "UPDATED_REMARK" DATE
  "OLD_REMARK" "VARCHAR2(500 BYTE)"
  "UPDATED_REMARK_STAFF" NUMBER
  "OLDSELL" NUMBER
  "OLDCOST" NUMBER
  "OLDPRICE" NUMBER
  "OLDPROFIT" NUMBER
  "TYPE_WINSPEED" "CHAR(10 BYTE)"
  "CONTRACT_STATUS" "VARCHAR2(20 CHAR)"
  "UNI_TRANSACTION" "VARCHAR2(100 CHAR)"
  "DRAFT_ID" NUMBER
  "JOB_ID" NUMBER
  "TAX_NAME" "VARCHAR2(255 BYTE)"
  "TAX_ADDRESS" "VARCHAR2(255 BYTE)"
  "TAXID" "VARCHAR2(50 BYTE)"
  "TAX_STATUS" "VARCHAR2(20 BYTE)" [not null, default: 'รอออกใบกำกับภาษี']
  "TAX_ISSUE_DATE" DATE
  "WINSPEED_STATUS" "VARCHAR2(20 BYTE)" [not null, default: 'รอส่ง']
  "TAX_ISSUE_TYPE" "VARCHAR2(20 BYTE)"
  "DELIVERY_NO" "VARCHAR2(20 BYTE)"
  "DUE_DATE" DATE
  "FLAG_SEND_PRODUCT" "CHAR(1 BYTE)"
  "SEND_DATE" DATE
  "SPARE_STATUS" "VARCHAR2(20 BYTE)"
  "SPARE_DATE" DATE
  "Z_RECEIPT_DUP_SUFFIX" "VARCHAR2(10 BYTE)"
  "Z_RECEIPT_NO" "VARCHAR2(20 BYTE)"
  "RECEIPT_NO_TMP" "VARCHAR2(50 BYTE)"
  "BANKLIST_RECEIPT" NUMBER
  "TRANSFER_DATE_RECEIPT" DATE
  "MYSQL_FEE" NUMBER
  "CHK_ABLE" "VARCHAR2(20 BYTE)"
  "DESCRIPTION_LOSE" "VARCHAR2(255 BYTE)"
  "TECH_STAFFID" NUMBER
  "APPROVE_ID" NUMBER
  "DIRECT_REMARK" "VARCHAR2(255 BYTE)"
  "PAGE_GROUP_ID" NUMBER
  "PAYMENT_TERM" NUMBER(3,0)
  "SPARE_STAFF_ID" NUMBER
  "PRINT_NUM" NUMBER [default: 0]
  "PERIOD_MY" "VARCHAR2(100 BYTE)"
  "PRIVATE_REMARK" "VARCHAR2(500 BYTE)"
  "STATUS_APPROVE" "VARCHAR2(20 BYTE)" [note: 'WA = Wait accounting, WF = Wait Finance, A = Approve']
  "STAFF_APPROVE" "VARCHAR2(50 BYTE)"
  "TIME_APPROVE" DATE
  "FREE_APPROVE" "VARCHAR2(20 BYTE)" [note: 'C = รอกดยืนยันของแถมปิดสัญญา , O = รอกดยืนยันของแถมปิดสัญญา ,CC = ยินยันปิดสัญญา ,CO = ยินยันเปิดสัญญา']
  "TIME_FREE_APPROVE" DATE
  "REASON_APPROVE" "VARCHAR2(150 BYTE)"

  Checks {
    `spare_status in ('รอตัดอะไหล่','ไม่ตัดอะไหล่','ตัดอะไหล่เสร็จสิ้น')` [name: 'CHK_SELL_SPARESTATUS']
    `"ID" IS NOT NULL` [name: 'SYS_C006573']
    `"SELL_DATE" IS NOT NULL` [name: 'SYS_C006574']
    `"SELL_STAFF" IS NOT NULL` [name: 'SYS_C006575']
    `"SHOP_ID" IS NOT NULL` [name: 'SYS_C006576']
    `"COMPANY_ID" IS NOT NULL` [name: 'SYS_C006577']
    `"CONTRACT_ID" IS NOT NULL` [name: 'SYS_C006578']
    `"SELL_TYPE" IS NOT NULL` [name: 'SYS_C006579']
    `"TAX_STATUS" IS NOT NULL` [name: 'SYS_C006580']
    `"WINSPEED_STATUS" IS NOT NULL` [name: 'SYS_C006581']
  }

  Indexes {
    ID [pk, name: "PK_SELL"]
    (PERIOD_MY, PAGE_GROUP_ID) [name: "SIAMCHAI_STOCK"]
    COMPANY_ID [name: "SIAMCHAI_STOCK"]
    FINANCE_STAFF_ID [name: "SIAMCHAI_STOCK"]
    SELL_ON_CASH [name: "SIAMCHAI_STOCK"]
    (PERIOD_MY, PAGE_GROUP_ID, ID) [name: "SIAMCHAI_STOCK"]
    CONTRACT_ID [name: "SIAMCHAI_STOCK"]
    CONTRACT_REF [name: "SIAMCHAI_STOCK"]
    (FINANCE_STAFF_ID, PAYMENT_TERM) [name: "SIAMCHAI_STOCK"]
    SELL_STAFF [name: "SIAMCHAI_STOCK"]
    SHOP_ID [name: "SIAMCHAI_STOCK"]
    `TO_DATE(TO_CHAR("SELL_DATE",'ddmmyyyy'),'ddmmyyyy')` [name: "SIAMCHAI_STOCK"]
    SALES_STAFF_ID [name: "SIAMCHAI_STOCK"]
    `TO_DATE(TO_CHAR("SELL_DATE",'mmyyyy'),'mmyyyy')` [name: "SIAMCHAI_STOCK"]
    `TO_DATE(TO_CHAR("SYSTEM_DATE",'mmyyyy'),'mmyyyy')` [name: "SIAMCHAI_STOCK"]
    (STATUS, `NVL("CONTRACT_ID",0)`) [name: "SIAMCHAI_STOCK"]
    (`TO_DATE(TO_CHAR("SELL_DATE",'ddmmyyyy'),'ddmmyyyy')`, SELL_ON_CASH) [name: "SIAMCHAI_STOCK"]
    `TO_DATE(TO_CHAR("SELL_DATE",'yyyy-mm-dd'),'yyyy-mm-dd')` [name: "SIAMCHAI_STOCK"]
    `TO_DATE(TO_CHAR("SYSTEM_DATE",'yyyy-mm-dd'),'yyyy-mm-dd')` [name: "SIAMCHAI_STOCK"]
    MYSQL_CONTRACT_CODE [name: "SIAMCHAI_STOCK"]
    SELL_DATE [name: "SIAMCHAI_STOCK"]
    PAGE_GROUP_ID [name: "SIAMCHAI_STOCK"]
    SPARE_DATE [name: "SIAMCHAI_STOCK"]
    STATUS [name: "SIAMCHAI_STOCK"]
    PERIOD_MY [name: "SIAMCHAI_STOCK"]
    SYSTEM_DATE [name: "SIAMCHAI_STOCK"]
    UNI_TRANSACTION [unique, name: "SIAMCHAI_STOCK"]
    RECEIPT_NO_TMP [unique, name: "SIAMCHAI_STOCK"]
  }
}

Table "SIAMCHAI_STOCK"."SELL_DETAIL" {
  "ID" NUMBER [not null]
  "SELL_ID" NUMBER
  "PRODUCT_ID" NUMBER [not null]
  "COMPANY_ID" NUMBER [not null]
  "SHOP_ID" NUMBER [not null]
  "PARENT_ID" NUMBER
  "BARCODE" "VARCHAR2(20 BYTE)" [not null]
  "SERIAL" "VARCHAR2(50 BYTE)"
  "SPEC" "VARCHAR2(100 BYTE)"
  "COST" NUMBER(10,2) [default: 0]
  "PRICE" NUMBER(10,2)
  "VAT" NUMBER(10,2) [default: 0]
  "STATUS" "VARCHAR2(10 BYTE)" [default: 'OK']
  "QTY" NUMBER [default: 1]
  "QTY_YN" "CHAR(1 BYTE)" [default: 'N']
  "MIN_PRICE" NUMBER(10,2)
  "INSTALLATION_COST" NUMBER(10,2)
  "INSTALLATION_YN" "CHAR(1 BYTE)"
  "FROM_RETURN" "CHAR(1 BYTE)"
  "FROM_RETURN_ID" NUMBER
  "COST_TYPE" "VARCHAR2(10 BYTE)" [default: 'AVERAGE']
  "STOCKIN_DATE" DATE
  "PO_COST" NUMBER(10,2)
  "OUT_INSTALLATION" NUMBER(10,2)
  "IN_INSTALLATION" NUMBER(10,2)
  "INSTALLATION_STATUS" "VARCHAR2(30 BYTE)"
  "P_BONUS" "CHAR(1 CHAR)" [default: 'N']
  "WINSPEED_PRICE" NUMBER(10,2)
  "FLAG_DUP" "CHAR(1 BYTE)"
  "FLAG_MIN" "CHAR(1 BYTE)" [not null, default: 'N']
  "FLAG_CANCELCONT" "VARCHAR2(1 BYTE)" [note: 'flagเมื่อเคยปิดสัญญาแล้ว']
  "STATUS_TAX" "VARCHAR2(1 BYTE)" [note: 'สถานะออกใบกำกับภาษี']
  "TECH_STAFFID" NUMBER
  "REBATE_SELL_CN" "CHAR(1 BYTE)" [default: 'N', note: 'Y = Rebate , N = No Rebate']
  "SELL_PAGE" "VARCHAR2(2 BYTE)" [note: 'NS = Normal Sell, PD = Purchasing Department, WD = Warehouse Repaire Department']
  "MYSQL_MSWP_ID" NUMBER(10,2)
  "REPAIR_REQUEST_ID" NUMBER
  "REPAIR_REQUEST_STATUS" "VARCHAR2(255 BYTE)" [default: 'N']
  "REPAIR_STATUS" "VARCHAR2(255 BYTE)"

  Checks {
    `"ID" IS NOT NULL` [name: 'SYS_C006584']
    `"PRODUCT_ID" IS NOT NULL` [name: 'SYS_C006585']
    `"COMPANY_ID" IS NOT NULL` [name: 'SYS_C006586']
    `"SHOP_ID" IS NOT NULL` [name: 'SYS_C006587']
    `"BARCODE" IS NOT NULL` [name: 'SYS_C006588']
    `"FLAG_MIN" IS NOT NULL` [name: 'SYS_C006589']
  }

  Indexes {
    ID [pk, name: "PK_SELL_DETAIL"]
    (SELL_ID, BARCODE, P_BONUS, FLAG_DUP) [unique, name: "AK_KEY_2_SELL_1"]
    (SELL_ID, PRICE, COST, QTY) [name: "SIAMCHAI_STOCK"]
    (PRODUCT_ID, SHOP_ID) [name: "SIAMCHAI_STOCK"]
    SHOP_ID [name: "SIAMCHAI_STOCK"]
    (SHOP_ID, PRODUCT_ID) [name: "SIAMCHAI_STOCK"]
    SERIAL [name: "SIAMCHAI_STOCK"]
    (SELL_ID, ID) [name: "SIAMCHAI_STOCK"]
    BARCODE [name: "SIAMCHAI_STOCK"]
    COMPANY_ID [name: "SIAMCHAI_STOCK"]
    (COST, QTY, SELL_ID, ID) [name: "SIAMCHAI_STOCK"]
    SELL_ID [name: "SIAMCHAI_STOCK"]
    PRODUCT_ID [name: "SIAMCHAI_STOCK"]
    INSTALLATION_STATUS [name: "SIAMCHAI_STOCK"]
    (COMPANY_ID, SHOP_ID, BARCODE) [name: "SIAMCHAI_STOCK"]
    REPAIR_REQUEST_ID [name: "SIAMCHAI_STOCK"]
    (ID, SELL_ID, PRICE) [name: "SIAMCHAI_STOCK"]
    (ID, SELL_ID, INSTALLATION_COST) [name: "SIAMCHAI_STOCK"]
    MYSQL_MSWP_ID [name: "SIAMCHAI_STOCK"]
  }
}

Table "SIAMCHAI_STOCK"."PRODUCT" {
  "ID" NUMBER [not null, note: 'primary key']
  "CODE" "VARCHAR2(255 CHAR)" [note: '??????????']
  "DESCRIPTION" "VARCHAR2(255 CHAR)" [note: '??????????']
  "REMARK" "VARCHAR2(200 CHAR)" [note: '????????']
  "REGISTER" "CHAR(1 CHAR)" [note: 'Requiry Serial']
  "GROUP_ID" NUMBER [note: 'product group']
  "REQUIRE_APP" "CHAR(1 CHAR)" [note: '?????????????????????']
  "COST" NUMBER [default: 0, note: '???????']
  "PRICE" NUMBER [default: 0, note: '???????']
  "BRAND" "VARCHAR2(100 CHAR)" [note: '??????']
  "INSTALLATION_COST" NUMBER(10,2)
  "PU_PRODUCT_ID" NUMBER
  "EAN_YN" "CHAR(1 CHAR)"
  "APPROVE_PRODUCT" "CHAR(1 CHAR)"
  "SCS_CHECK" "CHAR(1 CHAR)" [default: 'N']
  "UPDATE_DATE" DATE
  "QTY_YN" "CHAR(1 CHAR)"
  "UPDATE_STAFF" NUMBER
  "OLD_QTY_YN" "CHAR(1 CHAR)"
  "INSTALLATION_YN" "CHAR(1 CHAR)"
  "PRODUCT_BRAND_ID" NUMBER
  "PRODUCT_MODEL_ID" NUMBER
  "PRODUCT_CATEGORY_ID" NUMBER
  "PRODUCT_SIZE_ID" NUMBER
  "PRODUCT_TYPE_ID" NUMBER
  "PRODUCT_UNIT_ID" NUMBER
  "PRODUCT_GROUP_ID" NUMBER
  "SPEC" "VARCHAR2(255 BYTE)"
  "MYSQL_ID" NUMBER
  "STOCK_QTY" NUMBER
  "STOCK_BARCODE" "VARCHAR2(255 BYTE)"
  "STATUS" "VARCHAR2(10 CHAR)" [not null, default: 'ACTIVE']
  "VAT_YN" "CHAR(1 BYTE)" [not null, default: 'N']
  "VAT" NUMBER
  "Z_PRODUCT_TYPE_ID" NUMBER
  "PRODUCT_RESERVE" "CHAR(1 BYTE)"

  Checks {
    `"ID" IS NOT NULL` [name: 'SYS_C006471']
    `"STATUS" IS NOT NULL` [name: 'SYS_C006472']
    `"VAT_YN" IS NOT NULL` [name: 'SYS_C006473']
  }

  Indexes {
    ID [pk, name: "PK_PRODUCT"]
    (PRODUCT_BRAND_ID, PRODUCT_MODEL_ID, PRODUCT_CATEGORY_ID, PRODUCT_SIZE_ID, PRODUCT_TYPE_ID, PRODUCT_UNIT_ID) [name: "SIAMCHAI_STOCK"]
    PU_PRODUCT_ID [name: "SIAMCHAI_STOCK"]
    GROUP_ID [name: "SIAMCHAI_STOCK"]
  }
}

Table "SIAMCHAI_STOCK"."PU_PRODUCT" {
  "ID" NUMBER [not null]
  "PU_DESCRIPTION" "VARCHAR2(255 BYTE)"
  "BRAND" "VARCHAR2(100 BYTE)"
  "GROUP_ID" NUMBER
  "CODE" "VARCHAR2(255 BYTE)"
  "REGISTER" "CHAR(1 BYTE)"
  "P_MODEL" "VARCHAR2(255 BYTE)"
  "MYSQL_ID" NUMBER
  "CONTROL" "VARCHAR2(30 BYTE)"
  "PRODUCT_MODEL_ID" NUMBER
  "PRODUCT_BRAND_ID" NUMBER
  "PRODUCT_CATEGORY_ID" NUMBER
  "PRODUCT_SIZE_ID" NUMBER
  "PRODUCT_TYPE_ID" NUMBER
  "VAT_YN" "CHAR(1 BYTE)" [not null, default: 'N']
  "VAT" NUMBER
  "LENGTH_SERIAL" NUMBER(10,0) [note: 'กำหนดความยาว serial']
  "PREFIX_SERIAL" "VARCHAR2(255 BYTE)" [note: 'กำหนดคำนำหน้า serial']
  "CHECK_SERIAL" "CHAR(1 BYTE)" [not null, default: 'Y']

  Checks {
    `"CHECK_SERIAL" IS NOT NULL` [name: 'SYS_C00139588']
    `"VAT_YN" IS NOT NULL` [name: 'SYS_C006512']
  }

  Indexes {
    ID [pk, name: "PU_PRODUCT_PK"]
    MYSQL_ID [name: "SIAMCHAI_STOCK"]
  }
}

Table "SIAMCHAI_STOCK"."REQ_TRANSFER" {
  "ID" NUMBER [not null]
  "SYSTEM_DATE" DATE [not null]
  "SYSTEM_STAFF" NUMBER [not null]
  "UPDATE_DATE" DATE
  "UPDATE_STAFF" NUMBER
  "SHOP_ID" NUMBER [not null]
  "REQ_FROM_SHOP_ID" NUMBER [not null]
  "PRODUCT_ID" NUMBER [not null]
  "QTY" NUMBER [not null]
  "DELIVERY_DATE" DATE [not null]
  "STATUS" "VARCHAR2(50 BYTE)" [not null, default: 'ขอโอนสินค้า']
  "CURRENT_STOCK" NUMBER [not null]
  "RECEIVE_STAFF" NUMBER
  "RECEIVE_DATE" DATE
  "TRANSFER_STAFF" NUMBER
  "TRANSFER_DATE" DATE
  "VOID_STAFF" NUMBER
  "VOID_REMARK" "VARCHAR2(200 BYTE)"

  Checks {
    `"ID" IS NOT NULL` [name: 'SYS_C006538']
    `"SYSTEM_DATE" IS NOT NULL` [name: 'SYS_C006539']
    `"SYSTEM_STAFF" IS NOT NULL` [name: 'SYS_C006540']
    `"SHOP_ID" IS NOT NULL` [name: 'SYS_C006541']
    `"REQ_FROM_SHOP_ID" IS NOT NULL` [name: 'SYS_C006542']
    `"PRODUCT_ID" IS NOT NULL` [name: 'SYS_C006543']
    `"QTY" IS NOT NULL` [name: 'SYS_C006544']
    `"DELIVERY_DATE" IS NOT NULL` [name: 'SYS_C006545']
    `"STATUS" IS NOT NULL` [name: 'SYS_C006546']
    `"CURRENT_STOCK" IS NOT NULL` [name: 'SYS_C006547']
  }

  Indexes {
    ID [pk, name: "SYS_C006548"]
    REQ_FROM_SHOP_ID [name: "SIAMCHAI_STOCK"]
    SHOP_ID [name: "SIAMCHAI_STOCK"]
    STATUS [name: "SIAMCHAI_STOCK"]
  }
}

Table "SIAMCHAI_STOCK"."RETURNX" {
  "ID" NUMBER [not null]
  "RETURN_DATE" DATE [not null]
  "RETURN_STAFF" NUMBER [not null]
  "SELL_ID" NUMBER
  "SHOP_ID" NUMBER [not null]
  "REMARK" "VARCHAR2(255 CHAR)"
  "RETURN_STATUS" "VARCHAR2(20 CHAR)"
  "PRODUCT_CONDITION" "VARCHAR2(255 CHAR)"
  "SYSTEM_DATE" DATE
  "CASH" NUMBER
  "CR_CARD" NUMBER
  "TRANSFER" NUMBER
  "FINANCE_USED" "CHAR(1 BYTE)" [not null, default: 'N']
  "CHK_CASH" "CHAR(1 BYTE)" [not null, default: 'N']
  "AMOUNT_WINSPEED" NUMBER
  "TYPE_WINSPEED" "CHAR(10 BYTE)"
  "UNI_TRANSACTION" "VARCHAR2(59 CHAR)"
  "NEW_BARCODE" "VARCHAR2(20 CHAR)"
  "BANKLIST_RECEIPT" NUMBER
  "BK_REMARK" "VARCHAR2(255 BYTE)"
  "TRANSFER_DATE_RECEIPT" DATE
  "CHANGE_REDEEM" "VARCHAR2(200 CHAR)" [default: 'N']
  "CHK_ABLE" "VARCHAR2(255 BYTE)"
  "DESCRIPTION_LOSE" "VARCHAR2(255 BYTE)"
  "VOID_TYPE" "VARCHAR2(50 BYTE)"

  Checks {
    `"ID" IS NOT NULL` [name: 'SYS_C006549']
    `"RETURN_DATE" IS NOT NULL` [name: 'SYS_C006550']
    `"RETURN_STAFF" IS NOT NULL` [name: 'SYS_C006551']
    `"SHOP_ID" IS NOT NULL` [name: 'SYS_C006552']
    `"FINANCE_USED" IS NOT NULL` [name: 'SYS_C006553']
    `"CHK_CASH" IS NOT NULL` [name: 'SYS_C006554']
  }

  Indexes {
    ID [pk, name: "PK_RETURNX"]
    (RETURN_DATE, RETURN_STAFF, SELL_ID, SHOP_ID) [unique, name: "UNI_RETURN"]
    `TO_CHAR("RETURN_DATE",'mmyyyy')` [name: "SIAMCHAI_STOCK"]
    `TO_DATE(TO_CHAR("RETURN_DATE",'mmyyyy'),'mmyyyy')` [name: "SIAMCHAI_STOCK"]
    `TO_CHAR("RETURN_DATE",'yyyymmdd')` [name: "SIAMCHAI_STOCK"]
    (RETURN_DATE, SELL_ID) [name: "SIAMCHAI_STOCK"]
    (SELL_ID, RETURN_DATE) [name: "SIAMCHAI_STOCK"]
    (SELL_ID, RETURN_DATE, RETURN_STATUS) [name: "SIAMCHAI_STOCK"]
    SHOP_ID [name: "SIAMCHAI_STOCK"]
    `TO_DATE(TO_CHAR("RETURN_DATE",'ddmmyyyy'),'ddmmyyyy')` [name: "SIAMCHAI_STOCK"]
    (SELL_ID, FINANCE_USED) [name: "SIAMCHAI_STOCK"]
    `TO_DATE(TO_CHAR("RETURN_DATE",'yyyy-mm-dd'),'yyyy-mm-dd')` [name: "SIAMCHAI_STOCK"]
    RETURN_STATUS [name: "SIAMCHAI_STOCK"]
    RETURN_DATE [name: "SIAMCHAI_STOCK"]
    RETURN_STAFF [name: "SIAMCHAI_STOCK"]
    UNI_TRANSACTION [unique, name: "SIAMCHAI_STOCK"]
  }
}

Table "SIAMCHAI_STOCK"."RETURNX_DETAIL" {
  "ID" NUMBER [not null]
  "RETURN_ID" NUMBER
  "PRODUCT_ID" NUMBER [not null]
  "COMPANY_ID" NUMBER [not null]
  "SHOP_ID" NUMBER [not null]
  "PARENT_ID" NUMBER
  "BARCODE" "VARCHAR2(20 BYTE)" [not null]
  "SERIAL" "VARCHAR2(50 BYTE)"
  "SPEC" "VARCHAR2(100 BYTE)"
  "COST" NUMBER(10,2) [default: 0]
  "PRICE" NUMBER(10,2)
  "VAT" NUMBER(10,2) [default: 0]
  "STATUS" "VARCHAR2(10 BYTE)" [default: 'OK']
  "QTY" NUMBER [default: 1]
  "QTY_YN" "CHAR(1 BYTE)" [default: 'N']
  "PO_COST" NUMBER(10,2)
  "SELL_DETAIL_ID" NUMBER
  "PRODUCT_STATUS" "VARCHAR2(255 BYTE)"
  "STATUS_BARCODE" "CHAR(1 BYTE)" [default: 'Y']
  "FLAG_DUP" "CHAR(1 BYTE)"
  "REBATE_DETAIL_ID" NUMBER(38,0)
  "REPAIR_REQUEST_ID" NUMBER
  "REPAIR_REQUEST_STATUS" "VARCHAR2(255 BYTE)" [default: 'N']
  "REPAIR_STATUS" "CHAR(255 CHAR)"

  Checks {
    `"ID" IS NOT NULL` [name: 'SYS_C006557']
    `"PRODUCT_ID" IS NOT NULL` [name: 'SYS_C006558']
    `"COMPANY_ID" IS NOT NULL` [name: 'SYS_C006559']
    `"SHOP_ID" IS NOT NULL` [name: 'SYS_C006560']
    `"BARCODE" IS NOT NULL` [name: 'SYS_C006561']
  }

  Indexes {
    ID [pk, name: "PK_RETURNX_DETAIL"]
    (RETURN_ID, BARCODE, STATUS_BARCODE, FLAG_DUP) [unique, name: "AK_KEY_2_RETURNX_2"]
    SELL_DETAIL_ID [unique, name: "UNI_SELL_DETAIL"]
    REPAIR_REQUEST_ID [name: "SIAMCHAI_STOCK"]
    RETURN_ID [name: "SIAMCHAI_STOCK"]
    (RETURN_ID, SELL_DETAIL_ID) [name: "SIAMCHAI_STOCK"]
    SERIAL [name: "SIAMCHAI_STOCK"]
    BARCODE [name: "SIAMCHAI_STOCK"]
    SHOP_ID [name: "SIAMCHAI_STOCK"]
  }
}

Table "SIAMCHAI_STOCK"."STOCK_CUS" {
  "ID" NUMBER [not null]
  "PRODUCT_ID" NUMBER [not null]
  "COMPANY_ID" NUMBER [not null]
  "SHOP_ID" NUMBER [default: 0]
  "DATE_IN" DATE [not null]
  "PARENT_ID" NUMBER
  "REF_ID" NUMBER [not null, note: 'If ref master = Sales then Ref_Id = Sell_Id']
  "REF_MASTER" "VARCHAR2(30 BYTE)" [not null]
  "BARCODE" "VARCHAR2(20 BYTE)" [not null]
  "SERIAL" "VARCHAR2(100 BYTE)"
  "SPEC" "VARCHAR2(100 BYTE)"
  "COST" NUMBER(10,2) [default: 0]
  "PRICE" NUMBER(10,2)
  "VAT" NUMBER(10,2) [default: 0]
  "STATUS" "VARCHAR2(10 BYTE)" [default: 'OK']
  "APP" "CHAR(1 BYTE)" [default: 'N']
  "QTY" NUMBER [default: 1]
  "QTY_YN" "CHAR(1 BYTE)" [default: 'N']
  "PO_COST" NUMBER(10,2)
  "RECOMMENDED_PRICE" NUMBER(10,2)
  "COST_TYPE" "VARCHAR2(10 BYTE)" [default: 'AVERAGE']
  "STOCK_REMARK" "VARCHAR2(255 CHAR)"
  "OLD_COST" NUMBER(38,4) [note: 'OLD Cost before rebate']
  "REPAIR_REQUEST_ID" NUMBER
  "REPAIR_REQUEST_STATUS" "VARCHAR2(255 BYTE)" [default: 'N']

  Checks {
    `"ID" IS NOT NULL` [name: 'SYS_C006629']
    `"PRODUCT_ID" IS NOT NULL` [name: 'SYS_C006630']
    `"COMPANY_ID" IS NOT NULL` [name: 'SYS_C006631']
    `"DATE_IN" IS NOT NULL` [name: 'SYS_C006632']
    `"REF_ID" IS NOT NULL` [name: 'SYS_C006633']
    `"REF_MASTER" IS NOT NULL` [name: 'SYS_C006634']
    `"BARCODE" IS NOT NULL` [name: 'SYS_C006635']
  }

  Indexes {
    ID [pk, name: "PK_STOCK_CUS"]
    BARCODE [name: "SIAMCHAI_STOCK"]
    PRODUCT_ID [name: "SIAMCHAI_STOCK"]
    COMPANY_ID [name: "SIAMCHAI_STOCK"]
    (SHOP_ID, SERIAL) [name: "SIAMCHAI_STOCK"]
    (BARCODE, SHOP_ID) [name: "SIAMCHAI_STOCK"]
    REF_ID [name: "SIAMCHAI_STOCK"]
    REPAIR_REQUEST_ID [name: "SIAMCHAI_STOCK"]
  }
}

Table "SIAMCHAI_STOCK"."STOCK_IN" {
  "ID" NUMBER [not null]
  "COMPANY_ID" NUMBER [not null]
  "REF_INV" "VARCHAR2(20 CHAR)" [not null]
  "REF_DATE" DATE [not null]
  "REMARK" "VARCHAR2(100 CHAR)"
  "SHOP_ID" NUMBER [not null]
  "TIMESTAMP" DATE [not null]
  "STAFF_ID" NUMBER [not null]
  "PO_NO" "VARCHAR2(20 CHAR)"
  "PO_DATE" DATE
  "PO_ID" NUMBER
  "FROM_JOB" "VARCHAR2(3 CHAR)"
  "OLD_INV" "VARCHAR2(20 CHAR)"
  "STAFF_INV" NUMBER
  "UPDATE_INV_DATE" DATE
  "NOT_USE" "VARCHAR2(1 BYTE)" [not null, default: 'N']

  Checks {
    `"ID" IS NOT NULL` [name: 'SYS_C006637']
    `"COMPANY_ID" IS NOT NULL` [name: 'SYS_C006638']
    `"REF_INV" IS NOT NULL` [name: 'SYS_C006639']
    `"REF_DATE" IS NOT NULL` [name: 'SYS_C006640']
    `"SHOP_ID" IS NOT NULL` [name: 'SYS_C006641']
    `"TIMESTAMP" IS NOT NULL` [name: 'SYS_C006642']
    `"STAFF_ID" IS NOT NULL` [name: 'SYS_C006643']
    `"NOT_USE" IS NOT NULL` [name: 'SYS_C006644']
  }

  Indexes {
    ID [pk, name: "PK_STOCK_IN"]
    `TO_DATE(TO_CHAR("TIMESTAMP",'yyyy/mm/dd'),'yyyy/mm/dd')` [name: "SIAMCHAI_STOCK"]
    TIMESTAMP [name: "SIAMCHAI_STOCK"]
    `TO_DATE(TO_CHAR("TIMESTAMP",'yyyy-mm-dd'),'yyyy-mm-dd')` [name: "SIAMCHAI_STOCK"]
    COMPANY_ID [name: "SIAMCHAI_STOCK"]
    SHOP_ID [name: "SIAMCHAI_STOCK"]
    STAFF_ID [name: "SIAMCHAI_STOCK"]
    PO_ID [name: "SIAMCHAI_STOCK"]
    `TO_DATE(TO_CHAR("TIMESTAMP",'mmyyyy'),'mmyyyy')` [name: "SIAMCHAI_STOCK"]
  }
}

Table "SIAMCHAI_STOCK"."STOCK_SHOP" {
  "ID" NUMBER [not null]
  "PRODUCT_ID" NUMBER [not null]
  "COMPANY_ID" NUMBER [not null]
  "SHOP_ID" NUMBER [not null]
  "DATE_IN" DATE [not null]
  "PARENT_ID" NUMBER
  "REF_ID" NUMBER [not null]
  "REF_MASTER" "VARCHAR2(30 BYTE)" [not null]
  "BARCODE" "VARCHAR2(20 BYTE)" [not null]
  "SERIAL" "VARCHAR2(50 BYTE)"
  "SPEC" "VARCHAR2(100 BYTE)"
  "COST" NUMBER(10,2) [default: 0]
  "PRICE" NUMBER(10,2)
  "VAT" NUMBER(10,2) [default: 0]
  "STATUS" "VARCHAR2(10 BYTE)" [default: 'OK']
  "QTY" NUMBER [default: 1]
  "QTY_YN" "CHAR(1 BYTE)" [default: 'N']
  "TRANSFER_DETAIL_ID" NUMBER
  "PO_COST" NUMBER(10,2)
  "COST_TYPE" "VARCHAR2(10 BYTE)" [default: 'AVERAGE']
  "SCS_DATE_IN" DATE
  "MANUAL_DATE_IN" DATE
  "OLD_BARCODE" "VARCHAR2(10 BYTE)"
  "REMARK" "VARCHAR2(1000 BYTE)"
  "STOCK_REMARK" "VARCHAR2(255 CHAR)"
  "STOCKIN_DATE" DATE
  "SHOW_PRODUCT" "CHAR(1 BYTE)" [default: 'N', note: 'ตั้งค่าตัวโชว์']
  "VOID_REMARK" "VARCHAR2(100 BYTE)" [note: 'หมายเหตุการยกเลิกสินค้าตัวโชว์']
  "VOID_STAFF" NUMBER(10,0) [note: 'ผู้ดำเนินการ']
  "VOID_DATE" DATE [note: 'วันที่ดำเนินการ']
  "REPAIR_REQUEST_ID" NUMBER
  "REPAIR_REQUEST_STATUS" "VARCHAR2(255 BYTE)" [default: 'N']
  "REPAIR_STATUS" "VARCHAR2(255 BYTE)"

  Checks {
    `"ID" IS NOT NULL` [name: 'SYS_C006646']
    `"PRODUCT_ID" IS NOT NULL` [name: 'SYS_C006647']
    `"COMPANY_ID" IS NOT NULL` [name: 'SYS_C006648']
    `"SHOP_ID" IS NOT NULL` [name: 'SYS_C006649']
    `"DATE_IN" IS NOT NULL` [name: 'SYS_C006650']
    `"REF_ID" IS NOT NULL` [name: 'SYS_C006651']
    `"REF_MASTER" IS NOT NULL` [name: 'SYS_C006652']
    `"BARCODE" IS NOT NULL` [name: 'SYS_C006653']
  }

  Indexes {
    ID [pk, name: "PK_STOCK_SHOP"]
    PRODUCT_ID [name: "SIAMCHAI_STOCK"]
    (PRODUCT_ID, SHOP_ID) [name: "SIAMCHAI_STOCK"]
    (REF_ID, REF_MASTER) [name: "SIAMCHAI_STOCK"]
    SHOP_ID [name: "SIAMCHAI_STOCK"]
    SERIAL [name: "SIAMCHAI_STOCK"]
    BARCODE [name: "SIAMCHAI_STOCK"]
    (COST_TYPE, PRODUCT_ID) [name: "SIAMCHAI_STOCK"]
    (PRODUCT_ID, SHOP_ID, COMPANY_ID) [name: "SIAMCHAI_STOCK"]
    DATE_IN [name: "SIAMCHAI_STOCK"]
  }
}

Table "SIAMCHAI_STOCK"."STOCKIN_DETAIL" {
  "ID" NUMBER [not null]
  "STOCKIN_ID" NUMBER
  "PRODUCT_ID" NUMBER [not null, note: 'product_id']
  "COMPANY_ID" NUMBER [not null]
  "SHOP_ID" NUMBER [not null]
  "BARCODE" "VARCHAR2(20 CHAR)" [not null]
  "SERIAL" "VARCHAR2(50 CHAR)"
  "SPEC" "VARCHAR2(100 CHAR)"
  "COST" NUMBER(12,4) [default: 0]
  "PRICE" NUMBER(12,4)
  "VAT" NUMBER(12,4) [default: 0]
  "QTY" NUMBER [default: 1]
  "QTY_YN" "CHAR(1 CHAR)" [default: 'N']
  "PO_DETAIL_ID" NUMBER
  "VOUCHER_PAYMENT_STAFF" NUMBER
  "VOUCHER_PAYMENT_DATE" DATE
  "VOUCHER_PAYMENT_STATUS" "CHAR(1 CHAR)" [default: 'W']
  "VOUCHER_PAYMENT_REMARK" "VARCHAR2(255 CHAR)"
  "PO_COST" NUMBER(12,4)
  "COST_TYPE" "VARCHAR2(10 CHAR)" [default: 'AVERAGE']
  "DOC_REV" "CHAR(2 CHAR)"
  "VOUCHER_ID" NUMBER
  "PV_CODE" "VARCHAR2(20 BYTE)"
  "NOT_USE" "VARCHAR2(1 BYTE)"

  Checks {
    `"ID" IS NOT NULL` [name: 'SYS_C006622']
    `"PRODUCT_ID" IS NOT NULL` [name: 'SYS_C006623']
    `"COMPANY_ID" IS NOT NULL` [name: 'SYS_C006624']
    `"SHOP_ID" IS NOT NULL` [name: 'SYS_C006625']
    `"BARCODE" IS NOT NULL` [name: 'SYS_C006626']
  }

  Indexes {
    ID [pk, name: "PK_STOCKIN_DETAIL"]
    (STOCKIN_ID, SHOP_ID, PRODUCT_ID, BARCODE) [unique, name: "UNI_STOCKIN_DETAIL"]
    (BARCODE, NOT_USE) [unique, name: "SIAMCHAI_STOCK"]
    SERIAL [name: "SIAMCHAI_STOCK"]
    BARCODE [name: "SIAMCHAI_STOCK"]
    STOCKIN_ID [name: "SIAMCHAI_STOCK"]
    PO_DETAIL_ID [name: "SIAMCHAI_STOCK"]
    PRODUCT_ID [name: "SIAMCHAI_STOCK"]
    (VOUCHER_PAYMENT_STATUS, PV_CODE) [name: "SIAMCHAI_STOCK"]
  }
}

Table "SIAMCHAI_STOCK"."TRANSFER" {
  "ID" NUMBER [not null]
  "TRANS_DATE" DATE [not null]
  "TRANS_STAFF" NUMBER [not null]
  "FROM_SHOP_ID" NUMBER [not null]
  "TO_SHOP_ID" NUMBER [not null]
  "REMARK" "VARCHAR2(200 BYTE)"
  "RECEIVE_DATE" DATE
  "RECEIVE_STAFF" NUMBER
  "SHOW_RECEIVE" "CHAR(1 BYTE)" [default: 'N']
  "REQ_TRANSFER_ID" NUMBER
  "UNI_TRANSACTION" "VARCHAR2(50 CHAR)"
  "FOR_SELL_ID" NUMBER

  Checks {
    `"ID" IS NOT NULL` [name: 'SYS_C006672']
    `"TRANS_DATE" IS NOT NULL` [name: 'SYS_C006673']
    `"TRANS_STAFF" IS NOT NULL` [name: 'SYS_C006674']
    `"FROM_SHOP_ID" IS NOT NULL` [name: 'SYS_C006675']
    `"TO_SHOP_ID" IS NOT NULL` [name: 'SYS_C006676']
  }

  Indexes {
    ID [pk, name: "PK_TRANSFER"]
    (TRANS_DATE, TRANS_STAFF, FROM_SHOP_ID, TO_SHOP_ID, REQ_TRANSFER_ID) [unique, name: "UNI_TRANSFER"]
    `TO_CHAR("TRANS_DATE",'yyyymmdd')` [name: "SIAMCHAI_STOCK"]
    `TO_DATE(TO_CHAR("RECEIVE_DATE",'yyyy/mm/dd'),'yyyy/mm/dd')` [name: "SIAMCHAI_STOCK"]
    TO_SHOP_ID [name: "SIAMCHAI_STOCK"]
    REQ_TRANSFER_ID [name: "SIAMCHAI_STOCK"]
    `TO_DATE(TO_CHAR("TRANS_DATE",'mmyyyy'),'mmyyyy')` [name: "SIAMCHAI_STOCK"]
  }
}

Table "SIAMCHAI_STOCK"."TRANSFER_DETAIL" {
  "ID" NUMBER [not null]
  "TRANSFER_ID" NUMBER
  "PRODUCT_ID" NUMBER [not null]
  "COMPANY_ID" NUMBER [not null]
  "SHOP_ID" NUMBER [not null]
  "PARENT_ID" NUMBER
  "BARCODE" "VARCHAR2(20 BYTE)" [not null]
  "SERIAL" "VARCHAR2(50 BYTE)"
  "SPEC" "VARCHAR2(100 BYTE)"
  "COST" NUMBER(10,2) [default: 0]
  "PRICE" NUMBER(10,2)
  "VAT" NUMBER(10,2) [default: 0]
  "STATUS" "VARCHAR2(10 BYTE)" [default: 'OK']
  "QTY" NUMBER [default: 1]
  "QTY_YN" "CHAR(1 BYTE)" [default: 'N']
  "PO_COST" NUMBER(10,2)

  Checks {
    `"ID" IS NOT NULL` [name: 'SYS_C006679']
    `"PRODUCT_ID" IS NOT NULL` [name: 'SYS_C006680']
    `"COMPANY_ID" IS NOT NULL` [name: 'SYS_C006681']
    `"SHOP_ID" IS NOT NULL` [name: 'SYS_C006682']
    `"BARCODE" IS NOT NULL` [name: 'SYS_C006683']
  }

  Indexes {
    ID [pk, name: "PK_TRANSFER_DETAIL"]
    (TRANSFER_ID, BARCODE) [unique, name: "AK_KEY_2_TRANSFER"]
    BARCODE [name: "SIAMCHAI_STOCK"]
    TRANSFER_ID [name: "SIAMCHAI_STOCK"]
    SERIAL [name: "SIAMCHAI_STOCK"]
  }
}


Ref: "SIAMCHAI_STOCK"."TRANSFER"."REQ_TRANSFER_ID" < "SIAMCHAI_STOCK"."REQ_TRANSFER"."ID"

Ref: "SIAMCHAI_STOCK"."TRANSFER_DETAIL"."TRANSFER_ID" < "SIAMCHAI_STOCK"."TRANSFER"."ID"

Ref: "SIAMCHAI_STOCK"."STOCKIN_DETAIL"."STOCKIN_ID" < "SIAMCHAI_STOCK"."STOCK_IN"."ID"

Ref: "SIAMCHAI_STOCK"."RETURNX_DETAIL"."RETURN_ID" < "SIAMCHAI_STOCK"."RETURNX"."ID"

Ref: "SIAMCHAI_STOCK"."PRODUCT"."PU_PRODUCT_ID" < "SIAMCHAI_STOCK"."PU_PRODUCT"."ID"

Ref: "SIAMCHAI_STOCK"."STOCKIN_DETAIL"."PRODUCT_ID" < "SIAMCHAI_STOCK"."PRODUCT"."ID"

Ref: "SIAMCHAI_STOCK"."RETURNX_DETAIL"."PRODUCT_ID" < "SIAMCHAI_STOCK"."PRODUCT"."ID"

Ref: "SIAMCHAI_STOCK"."STOCK_SHOP"."PRODUCT_ID" < "SIAMCHAI_STOCK"."PRODUCT"."ID"

Ref: "SIAMCHAI_STOCK"."SELL_DETAIL"."SELL_ID" < "SIAMCHAI_STOCK"."SELL"."ID"

Ref: "SIAMCHAI_STOCK"."SELL_DETAIL"."PRODUCT_ID" < "SIAMCHAI_STOCK"."PRODUCT"."ID"

Ref: "SIAMCHAI_STOCK"."RETURNX"."SELL_ID" < "SIAMCHAI_STOCK"."SELL"."ID"

Ref: "SIAMCHAI_STOCK"."RETURNX_DETAIL"."SELL_DETAIL_ID" < "SIAMCHAI_STOCK"."SELL_DETAIL"."ID"

Ref: "SIAMCHAI_STOCK"."TRANSFER_DETAIL"."PRODUCT_ID" < "SIAMCHAI_STOCK"."PRODUCT"."ID"

Ref: "SIAMCHAI_STOCK"."TRANSFER"."FOR_SELL_ID" < "SIAMCHAI_STOCK"."SELL"."ID"

Ref: "SIAMCHAI_STOCK"."STOCK_CUS"."PRODUCT_ID" < "SIAMCHAI_STOCK"."PRODUCT"."ID"

Ref: "SIAMCHAI_STOCK"."STOCK_CUS"."REF_ID" < "SIAMCHAI_STOCK"."SELL"."ID"

Ref: "SIAMCHAI_STOCK"."STOCK_SHOP"."TRANSFER_DETAIL_ID" < "SIAMCHAI_STOCK"."TRANSFER_DETAIL"."ID"
Table "SIAMCHAI_STOCK"."MYSQL_STAFF" {
  "ID" NUMBER(10,0) [not null]
  "COM_ID" NUMBER(10,0) [default: 0]
  "USER" "VARCHAR2(20 BYTE)"
  "PASS" "VARCHAR2(36 BYTE)"
  "PASS2" "VARCHAR2(36 BYTE)" [default: '']
  "NICKNAME" "VARCHAR2(100 BYTE)"
  "DISPLAY_NAME" "VARCHAR2(100 BYTE)"
  "EMAIL" "VARCHAR2(100 BYTE)" [default: '']
  "LINE" "VARCHAR2(50 BYTE)" [default: '']
  "MOBILE" "VARCHAR2(10 BYTE)" [default: '']
  "DEPARTMENT_ID" NUMBER(11,0) [default: 0]
  "SHOP_ID" NUMBER(11,0) [default: 0]
  "REF_ID" NUMBER [default: 0]
  "SUFFIX_BARCODE" "VARCHAR2(6 BYTE)" [default: '']
  "COMMISSION_PCT" NUMBER(10,2) [default: 0]
  "LAST_LOGIN" DATE
  "LAST_IP" "VARCHAR2(100 BYTE)" [default: '']
  "IS_ADMIN" "VARCHAR2(3 BYTE)" [default: 'NO']
  "IS_ACTIVE" "VARCHAR2(3 BYTE)" [default: 'YES']
  "CREATED_AT" DATE
  "CREATED_BY" NUMBER(10,0) [default: 0]
  "UPDATED_AT" DATE
  "UPDATED_BY" NUMBER(10,0) [default: 0]
  "NATIONID" "VARCHAR2(13 BYTE)" [default: '']
  "WORK_TYPE" "VARCHAR2(3 BYTE)" [default: 'FRE']
  "BIRTHDAY" DATE
  "CHILDREN" NUMBER(2,0) [default: 0]
  "ACCOUNT" "VARCHAR2(50 BYTE)"
  "ADDRESS" "VARCHAR2(255 BYTE)"
  "DETAIL" "VARCHAR2(255 BYTE)"
  "ADDRESS_NO" "VARCHAR2(50 BYTE)"
  "ADDRESS_SOI" "VARCHAR2(50 BYTE)"
  "ADDRESS_TUMBON" "VARCHAR2(50 BYTE)"
  "ADDRESS_AMPHUR" "VARCHAR2(50 BYTE)"
  "ADDRESS_CITY" "VARCHAR2(50 BYTE)"
  "ZIPCODE" "VARCHAR2(5 BYTE)"
  "START_DATE" DATE
  "EM_CODE" "VARCHAR2(255 BYTE)"
  "BANK" "VARCHAR2(100 BYTE)"
  "MASTER_BANK_ID" NUMBER
  "END_DATE" DATE
  "IS_LOCK" "VARCHAR2(255 CHAR)"
  "BAGENUMBER" "VARCHAR2(255 BYTE)"
  "DONOT_LOCK" "VARCHAR2(255 BYTE)"
  "TIME_BRANCH" "VARCHAR2(255 BYTE)"
  "TITLENAME" "VARCHAR2(25 BYTE)"

  Checks {
    `"ID" IS NOT NULL` [name: 'SYS_C0052694']
  }

  Indexes {
    END_DATE [name: "SIAMCHAI_STOCK"]
    SHOP_ID [name: "SIAMCHAI_STOCK"]
    DISPLAY_NAME [name: "SIAMCHAI_STOCK"]
    ID [name: "SIAMCHAI_STOCK"]
  }
}

Table "SIAMCHAI_STOCK"."STAFF" {
  "ID" NUMBER [not null]
  "BARCODE" "VARCHAR2(20 BYTE)" [not null]
  "NICKNAME" "VARCHAR2(40 BYTE)" [not null]
  "FULLNAME" "VARCHAR2(100 BYTE)"
  "ADDRESS" "VARCHAR2(200 BYTE)"
  "TEL" "VARCHAR2(100 BYTE)"
  "SHOP_ID" NUMBER
  "PASSWD" "VARCHAR2(20 BYTE)"
  "ACTIVE" "CHAR(1 BYTE)"
  "VIEW_ALL" "CHAR(1 BYTE)" [not null, default: 'N']
  "MYSQLVIEWSTAFFID" NUMBER [not null, default: 0]
  "MYSQLVIEWSHOPID" NUMBER [not null, default: 0]
  "COMMISSION_PCT" NUMBER [not null, default: 0]
  "MAIN_SHOP" "CHAR(1 BYTE)" [default: 'Y']
  "IS_STAFF" "CHAR(1 BYTE)" [not null, default: 'Y']
  "STAFF_CHECK" "VARCHAR2(1 BYTE)" [not null, default: 'N']
  "EM_CODE" "VARCHAR2(255 BYTE)"
  "TIME_BRANCH" "VARCHAR2(255 BYTE)"

  Checks {
    `"ID" IS NOT NULL` [name: 'SYS_C006611']
    `"BARCODE" IS NOT NULL` [name: 'SYS_C006612']
    `"NICKNAME" IS NOT NULL` [name: 'SYS_C006613']
    `"VIEW_ALL" IS NOT NULL` [name: 'SYS_C006614']
    `"MYSQLVIEWSTAFFID" IS NOT NULL` [name: 'SYS_C006615']
    `"MYSQLVIEWSHOPID" IS NOT NULL` [name: 'SYS_C006616']
    `"COMMISSION_PCT" IS NOT NULL` [name: 'SYS_C006617']
    `"IS_STAFF" IS NOT NULL` [name: 'SYS_C006618']
    `"STAFF_CHECK" IS NOT NULL` [name: 'SYS_C006619']
  }

  Indexes {
    ID [pk, name: "PK_STAFF"]
    BARCODE [unique, name: "AK_KEY_2_STAFF"]
    EM_CODE [name: "SIAMCHAI_STOCK"]
    (MYSQLVIEWSTAFFID, MYSQLVIEWSHOPID) [name: "SIAMCHAI_STOCK"]
    IS_STAFF [name: "SIAMCHAI_STOCK"]
  }
}

Table "SIAMCHAI_STOCK"."PICK_SPARE" {
  "ID" NUMBER [not null]
  "CODE" "VARCHAR2(255 BYTE)" [not null]
  "STAFF_ID" NUMBER [not null]
  "REQUEST_DATE" DATE [not null]
  "REQUEST_STAFF_ID" NUMBER [not null]
  "SHOP_ID" NUMBER [not null]
  "SYSTEM_DATE" DATE
  "STATUS" "VARCHAR2(255 BYTE)"
  "REMARK" "VARCHAR2(255 BYTE)"

  Checks {
    `"ID" IS NOT NULL` [name: 'SYS_C0027444']
    `"CODE" IS NOT NULL` [name: 'SYS_C0027445']
    `"STAFF_ID" IS NOT NULL` [name: 'SYS_C0027446']
    `"REQUEST_DATE" IS NOT NULL` [name: 'SYS_C0027447']
    `"REQUEST_STAFF_ID" IS NOT NULL` [name: 'SYS_C0027448']
    `"SHOP_ID" IS NOT NULL` [name: 'SYS_C0027449']
  }

  Indexes {
    ID [pk, name: "SYS_C0027450"]
    CODE [unique, name: "SIAMCHAI_STOCK"]
  }
}

Table "SIAMCHAI_STOCK"."PICK_SPARE_DETAIL" {
  "ID" NUMBER [not null]
  "PICK_SPARE_ID" NUMBER [not null]
  "BARCODE" "VARCHAR2(255 BYTE)" [not null]
  "QTY" NUMBER [not null]

  Checks {
    `"ID" IS NOT NULL` [name: 'SYS_C0029936']
    `"PICK_SPARE_ID" IS NOT NULL` [name: 'SYS_C0029937']
    `"BARCODE" IS NOT NULL` [name: 'SYS_C0029938']
    `"QTY" IS NOT NULL` [name: 'SYS_C0029939']
  }

  Indexes {
    ID [pk, name: "SYS_C0029940"]
  }
}

Table "SIAMCHAI_STOCK"."PICK_SPARE_RETURN" {
  "ID" NUMBER [not null]
  "CODE" "VARCHAR2(255 BYTE)" [not null]
  "RETURN_STAFF_ID" NUMBER [not null]
  "REQUEST_STAFF_ID" NUMBER [not null]
  "SHOP_ID" NUMBER [not null]
  "RETURN_DATE" DATE [not null]
  "SYSTEM_DATE" DATE [not null]
  "REMARK" "VARCHAR2(255 BYTE)" [not null]

  Checks {
    `"CODE" IS NOT NULL` [name: 'SYS_C0035452']
    `"RETURN_STAFF_ID" IS NOT NULL` [name: 'SYS_C0035453']
    `"REQUEST_STAFF_ID" IS NOT NULL` [name: 'SYS_C0035454']
    `"SHOP_ID" IS NOT NULL` [name: 'SYS_C0035455']
    `"RETURN_DATE" IS NOT NULL` [name: 'SYS_C0035456']
    `"SYSTEM_DATE" IS NOT NULL` [name: 'SYS_C0035457']
    `"REMARK" IS NOT NULL` [name: 'SYS_C0035458']
  }

  Indexes {
    ID [pk, name: "SYS_C0035459"]
    CODE [unique, name: "UNI_RETURN_CODE"]
  }
}

Table "SIAMCHAI_STOCK"."PICK_SPARE_RETURN_DETAIL" {
  "ID" NUMBER [not null]
  "PICK_SPARE_RETURN_ID" NUMBER [not null]
  "BARCODE" "VARCHAR2(255 BYTE)" [not null]
  "QTY" NUMBER [not null]

  Checks {
    `"PICK_SPARE_RETURN_ID" IS NOT NULL` [name: 'SYS_C0035460']
    `"BARCODE" IS NOT NULL` [name: 'SYS_C0035461']
    `"QTY" IS NOT NULL` [name: 'SYS_C0035462']
  }

  Indexes {
    ID [pk, name: "SYS_C0035463"]
  }
}

Table "SIAMCHAI_STOCK"."SHOP" {
  "ID" NUMBER [not null]
  "CODE" "VARCHAR2(20 CHAR)" [not null]
  "NAME" "VARCHAR2(100 CHAR)" [not null]
  "LOCATION" "VARCHAR2(200 CHAR)"
  "TEL" "VARCHAR2(100 CHAR)"
  "FAX" "VARCHAR2(100 CHAR)"
  "ACTIVE" "CHAR(1 CHAR)" [default: 'Y']
  "SHOP_SALE" "CHAR(1 CHAR)" [not null, default: 'Y']
  "SCS_CODE" "VARCHAR2(50 CHAR)"
  "APPROVE_PRODUCT" "CHAR(1 CHAR)"
  "AUTO_PRINT_RECEIPT" "CHAR(1 CHAR)"
  "PREFIX_BARCODE" "VARCHAR2(4 CHAR)"
  "MYSQLSHOPID" NUMBER [not null, default: 0]
  "USE_SHOP" "CHAR(1 CHAR)"
  "SYSTEM_DATE" DATE
  "OPEN_DATE" DATE
  "NOT_USE" "CHAR(1 BYTE)" [not null, default: 'N']
  "INFO_USE" "VARCHAR2(1 BYTE)" [not null, default: 'Y']
  "WINSPEED" "VARCHAR2(1 CHAR)" [not null, default: 'Y']
  "AVERAGE_COST" "VARCHAR2(3 CHAR)" [not null, default: 'YES']
  "LAT" NUMBER(10,8)
  "LNG" NUMBER(11,8)
  "MYSQLPROVINCEID" NUMBER [not null, default: 0, note: 'รหัสจังหวัด']
  "MYSQLREGIONID" NUMBER [not null, default: 0, note: 'รหัสภูมิภาค']
  "HEAD_OFFICE" "CHAR(1 CHAR)" [not null, default: 'N', note: 'Y: สาขาดังกล่าวเป็นสำนักงานใหญ่ N: ไม่ใช่']
  "SHOP_ROWS" "VARCHAR2(100 BYTE)" [note: 'คูหา']

  Checks {
    `"ID" IS NOT NULL` [name: 'SYS_C006597']
    `"CODE" IS NOT NULL` [name: 'SYS_C006598']
    `"NAME" IS NOT NULL` [name: 'SYS_C006599']
    `"SHOP_SALE" IS NOT NULL` [name: 'SYS_C006600']
    `"MYSQLSHOPID" IS NOT NULL` [name: 'SYS_C006601']
    `"NOT_USE" IS NOT NULL` [name: 'SYS_C006602']
    `"INFO_USE" IS NOT NULL` [name: 'SYS_C006603']
    `"WINSPEED" IS NOT NULL` [name: 'SYS_C006604']
    `"AVERAGE_COST" IS NOT NULL` [name: 'SYS_C006605']
    `"MYSQLPROVINCEID" IS NOT NULL` [name: 'SYS_C006606']
    `"MYSQLREGIONID" IS NOT NULL` [name: 'SYS_C006607']
    `"HEAD_OFFICE" IS NOT NULL` [name: 'SYS_C006608']
  }

  Indexes {
    ID [pk, name: "PK_SHOP"]
    CODE [unique, name: "AK_KEY_2_SHOP"]
    MYSQLSHOPID [name: "SIAMCHAI_STOCK"]
    NOT_USE [name: "SIAMCHAI_STOCK"]
    AVERAGE_COST [name: "SIAMCHAI_STOCK"]
    INFO_USE [name: "SIAMCHAI_STOCK"]
  }
}


Ref: "SIAMCHAI_STOCK"."STAFF"."SHOP_ID" < "SIAMCHAI_STOCK"."SHOP"."ID"

Ref: "SIAMCHAI_STOCK"."MYSQL_STAFF"."SHOP_ID" < "SIAMCHAI_STOCK"."SHOP"."MYSQLSHOPID"

Ref: "SIAMCHAI_STOCK"."STAFF"."MYSQLVIEWSHOPID" < "SIAMCHAI_STOCK"."SHOP"."MYSQLSHOPID"

Ref: "SIAMCHAI_STOCK"."RETURNX_DETAIL"."SHOP_ID" < "SIAMCHAI_STOCK"."SHOP"."ID"

Ref: "SIAMCHAI_STOCK"."STOCK_CUS"."SHOP_ID" < "SIAMCHAI_STOCK"."SHOP"."ID"

Ref: "SIAMCHAI_STOCK"."SELL_DETAIL"."SHOP_ID" < "SIAMCHAI_STOCK"."SHOP"."ID"

Ref: "SIAMCHAI_STOCK"."RETURNX"."SHOP_ID" < "SIAMCHAI_STOCK"."SHOP"."ID"

Ref: "SIAMCHAI_STOCK"."PICK_SPARE_RETURN"."SHOP_ID" < "SIAMCHAI_STOCK"."SHOP"."ID"

Ref: "SIAMCHAI_STOCK"."PICK_SPARE"."SHOP_ID" < "SIAMCHAI_STOCK"."SHOP"."ID"

Ref: "SIAMCHAI_STOCK"."STOCK_SHOP"."SHOP_ID" < "SIAMCHAI_STOCK"."SHOP"."ID"

Ref: "SIAMCHAI_STOCK"."TRANSFER_DETAIL"."SHOP_ID" < "SIAMCHAI_STOCK"."SHOP"."ID"

Ref: "SIAMCHAI_STOCK"."STOCKIN_DETAIL"."SHOP_ID" < "SIAMCHAI_STOCK"."SHOP"."ID"

Ref: "SIAMCHAI_STOCK"."STOCK_IN"."SHOP_ID" < "SIAMCHAI_STOCK"."SHOP"."ID"

Ref: "SIAMCHAI_STOCK"."TRANSFER"."FROM_SHOP_ID" < "SIAMCHAI_STOCK"."SHOP"."ID"

Ref: "SIAMCHAI_STOCK"."TRANSFER"."TO_SHOP_ID" < "SIAMCHAI_STOCK"."SHOP"."ID"

Ref: "SIAMCHAI_STOCK"."PICK_SPARE"."STAFF_ID" < "SIAMCHAI_STOCK"."STAFF"."ID"

Ref: "SIAMCHAI_STOCK"."PICK_SPARE_DETAIL"."PICK_SPARE_ID" < "SIAMCHAI_STOCK"."PICK_SPARE"."ID"

Ref: "SIAMCHAI_STOCK"."PICK_SPARE_RETURN"."RETURN_STAFF_ID" < "SIAMCHAI_STOCK"."STAFF"."ID"

Ref: "SIAMCHAI_STOCK"."PICK_SPARE_RETURN_DETAIL"."PICK_SPARE_RETURN_ID" < "SIAMCHAI_STOCK"."PICK_SPARE_RETURN"."ID"

Ref: "SIAMCHAI_STOCK"."PICK_SPARE_RETURN"."REQUEST_STAFF_ID" < "SIAMCHAI_STOCK"."STAFF"."ID"

Ref: "SIAMCHAI_STOCK"."PICK_SPARE"."REQUEST_STAFF_ID" < "SIAMCHAI_STOCK"."STAFF"."ID"
Table "SIAMCHAI_STOCK"."TECHNICIAN_HOLD_SPARE" {
  "ID" NUMBER [not null]
  "STAFF_ID" NUMBER [not null]
  "PICK_SPARE_ID" NUMBER [not null]
  "SHOP_ID" NUMBER [not null]
  "BARCODE" "VARCHAR2(255 BYTE)" [not null]
  "QTY" NUMBER
  "UPDATE_DATE" DATE
  "UPDATE_STAFF" NUMBER
  "QTY_USE" NUMBER
  "CREATE_DATE" DATE
  "CREATE_STAFF" "VARCHAR2(255 BYTE)"

  Checks {
    `QTY_USE<=QTY` [name: 'CONST_001']
    `"STAFF_ID" IS NOT NULL` [name: 'SYS_C0029941']
    `"PICK_SPARE_ID" IS NOT NULL` [name: 'SYS_C0029942']
    `"SHOP_ID" IS NOT NULL` [name: 'SYS_C0029943']
    `"BARCODE" IS NOT NULL` [name: 'SYS_C0029944']
  }

  Indexes {
    ID [pk, name: "SYS_C0029945"]
    STAFF_ID [name: "SIAMCHAI_STOCK"]
    SHOP_ID [name: "SIAMCHAI_STOCK"]
    BARCODE [name: "SIAMCHAI_STOCK"]
  }
}


Ref: "SIAMCHAI_STOCK"."TECHNICIAN_HOLD_SPARE"."STAFF_ID" < "SIAMCHAI_STOCK"."STAFF"."ID"

Ref: "SIAMCHAI_STOCK"."TECHNICIAN_HOLD_SPARE"."SHOP_ID" < "SIAMCHAI_STOCK"."SHOP"."ID"

Ref: "SIAMCHAI_STOCK"."TECHNICIAN_HOLD_SPARE"."PICK_SPARE_ID" < "SIAMCHAI_STOCK"."PICK_SPARE"."ID"

Ref: "SIAMCHAI_STOCK"."STAFF"."MYSQLVIEWSTAFFID" < "SIAMCHAI_STOCK"."MYSQL_STAFF"."ID"
Table "SIAMCHAI_STOCK"."COMPANY" {
  "ID" NUMBER [not null]
  "TYPE" "CHAR(1 BYTE)" [not null]
  "CODE" "VARCHAR2(100 BYTE)" [not null]
  "NAME" "VARCHAR2(100 BYTE)" [not null]
  "ADDRESS" "VARCHAR2(200 BYTE)"
  "TEL" "VARCHAR2(100 BYTE)"
  "FAX" "VARCHAR2(100 BYTE)"
  "WEBSITE" "VARCHAR2(100 BYTE)"
  "CONTACT1" "VARCHAR2(100 BYTE)"
  "CONTACT1_REM" "VARCHAR2(200 BYTE)"
  "CONTACT2" "VARCHAR2(100 BYTE)"
  "CONTACT2_REM" "VARCHAR2(200 BYTE)"
  "REMARK" "VARCHAR2(255 BYTE)"
  "BIRTH_DAY" "VARCHAR2(2 BYTE)"
  "BIRTH_MONTH" "VARCHAR2(2 BYTE)"
  "BIRTH_YEAR" "VARCHAR2(4 BYTE)"
  "BILL_NAME" "VARCHAR2(100 BYTE)"
  "BILL_ADDR" "VARCHAR2(200 BYTE)"
  "DELIVERY_DETAIL" "VARCHAR2(255 BYTE)"
  "PAYMENT_DETAIL" "VARCHAR2(255 BYTE)"
  "INFORMATION" "VARCHAR2(200 BYTE)"
  "MEMO" "VARCHAR2(255 BYTE)"
  "CONTACT3" "VARCHAR2(100 BYTE)"
  "CONTACT4" "VARCHAR2(100 BYTE)"
  "CONTACT5" "VARCHAR2(100 BYTE)"
  "CONTACT6" "VARCHAR2(100 BYTE)"
  "CONTACT7" "VARCHAR2(100 BYTE)"
  "POSITION1" "VARCHAR2(100 BYTE)"
  "POSITION2" "VARCHAR2(100 BYTE)"
  "POSITION3" "VARCHAR2(100 BYTE)"
  "POSITION4" "VARCHAR2(100 BYTE)"
  "POSITION5" "VARCHAR2(100 BYTE)"
  "POSITION6" "VARCHAR2(100 BYTE)"
  "POSITION7" "VARCHAR2(100 BYTE)"
  "EMAIL1" "VARCHAR2(100 BYTE)"
  "EMAIL2" "VARCHAR2(100 BYTE)"
  "EMAIL3" "VARCHAR2(100 BYTE)"
  "EMAIL4" "VARCHAR2(100 BYTE)"
  "EMAIL5" "VARCHAR2(100 BYTE)"
  "EMAIL6" "VARCHAR2(100 BYTE)"
  "EMAIL7" "VARCHAR2(100 BYTE)"
  "TEL1" "VARCHAR2(100 BYTE)"
  "TEL2" "VARCHAR2(100 BYTE)"
  "TEL3" "VARCHAR2(100 BYTE)"
  "TEL4" "VARCHAR2(100 BYTE)"
  "TEL5" "VARCHAR2(100 BYTE)"
  "TEL6" "VARCHAR2(100 BYTE)"
  "TEL7" "VARCHAR2(100 BYTE)"
  "TAX_ID" "VARCHAR2(20 BYTE)"
  "NATIONID" "VARCHAR2(13 BYTE)"
  "APPROVE_YN" "CHAR(1 BYTE)" [not null, default: 'N']
  "MYSQL_ID" NUMBER
  "CREATED_BY" "VARCHAR2(100 BYTE)"
  "UPDATED_BY" "VARCHAR2(100 BYTE)"
  "CREATE_DATE" DATE [default: `sysdate`]
  "BIRTH_DATE" DATE
  "UPDATED_DATE" DATE [default: `sysdate`]
  "PASSPORT" "VARCHAR2(20 BYTE)"
  "O_WEB" "CHAR(1 BYTE)"
  "PAYMENT_OPTION_ID" NUMBER
  "COMPANY_CN_STATUS" "VARCHAR2(1 BYTE)" [note: 'สถานะการเลือกผู้จัดจำหน่ายหน้า CN']
  "COMPANY_PO_STATUS" "VARCHAR2(1 BYTE)" [note: 'สถานะการเลือกผู้จัดจำหน่ายหน้า PO']
  "FLAG_DELETE" "VARCHAR2(1 BYTE)" [default: 'N', note: 'delete ผู้จัดจำหน่าย เปลี่่ยนจาก delete เป็น flag']

  Checks {
    `"ID" IS NOT NULL` [name: 'SYS_C006272']
    `"TYPE" IS NOT NULL` [name: 'SYS_C006273']
    `"CODE" IS NOT NULL` [name: 'SYS_C006274']
    `"NAME" IS NOT NULL` [name: 'SYS_C006275']
    `"APPROVE_YN" IS NOT NULL` [name: 'SYS_C006276']
  }

  Indexes {
    ID [pk, name: "PK_COMPANY"]
    MYSQL_ID [unique, name: "uni_mysql_id"]
    CODE [name: "SIAMCHAI_STOCK"]
    NATIONID [name: "SIAMCHAI_STOCK"]
    TYPE [name: "SIAMCHAI_STOCK"]
    NAME [name: "SIAMCHAI_STOCK"]
    (ID, NAME, TEL, MYSQL_ID) [name: "SIAMCHAI_STOCK"]
    `REVERSE(LOWER("NAME"))` [name: "SIAMCHAI_STOCK"]
  }
}


Ref: "SIAMCHAI_STOCK"."STOCK_IN"."COMPANY_ID" < "SIAMCHAI_STOCK"."COMPANY"."ID"

Ref: "SIAMCHAI_STOCK"."STOCK_SHOP"."COMPANY_ID" < "SIAMCHAI_STOCK"."COMPANY"."ID"

Ref: "SIAMCHAI_STOCK"."STOCK_CUS"."COMPANY_ID" < "SIAMCHAI_STOCK"."COMPANY"."ID"

Ref: "SIAMCHAI_STOCK"."RETURNX_DETAIL"."COMPANY_ID" < "SIAMCHAI_STOCK"."COMPANY"."ID"

Ref: "SIAMCHAI_STOCK"."SELL"."COMPANY_ID" < "SIAMCHAI_STOCK"."COMPANY"."ID"

Ref: "SIAMCHAI_STOCK"."SELL_DETAIL"."COMPANY_ID" < "SIAMCHAI_STOCK"."COMPANY"."ID"

Ref: "SIAMCHAI_STOCK"."TRANSFER_DETAIL"."COMPANY_ID" < "SIAMCHAI_STOCK"."COMPANY"."ID"

Ref: "SIAMCHAI_STOCK"."STOCKIN_DETAIL"."COMPANY_ID" < "SIAMCHAI_STOCK"."COMPANY"."ID"

Ref: "SIAMCHAI_STOCK"."REQ_TRANSFER"."REQ_FROM_SHOP_ID" < "SIAMCHAI_STOCK"."SHOP"."ID"

Ref: "SIAMCHAI_STOCK"."SELL"."SHOP_ID" < "SIAMCHAI_STOCK"."SHOP"."ID"
Table "SIAMCHAI_OP"."PO" {
  "ID" NUMBER [not null, note: 'primary key']
  "CREATE_DATE" DATE [not null, note: '???????????????????']
  "CREATE_STAFF" NUMBER [not null, note: '???????????????????']
  "UPDATE_DATE" DATE [note: '?????????????????']
  "UPDATE_STAFF" NUMBER [note: '??????????????']
  "SALE_ORDER_ID" NUMBER [note: '?????? SO']
  "PO_NO" "VARCHAR2(20 BYTE)" [note: '?????? PO']
  "PO_DATE" DATE [not null, note: '?????? PO']
  "COMPANY_ID" NUMBER [not null, note: 'id ??????']
  "CONTACT_NAME" "VARCHAR2(200 BYTE)" [not null, note: '?????????????']
  "ADDRESS" "VARCHAR2(200 BYTE)" [not null, note: '?????????????']
  "TEL" "VARCHAR2(100 BYTE)" [not null, note: '????????']
  "FAX" "VARCHAR2(100 BYTE)" [not null, note: '??????????']
  "PAYMENT" "VARCHAR2(50 BYTE)" [not null, note: '???????????????????']
  "FREQUENCY" NUMBER [note: '??????? QT ???????????????? ? ???????????????']
  "DISCOUNT" NUMBER(10,2) [note: '??????']
  "VAT" NUMBER(10,2) [note: '?????????']
  "CHECK_VAT" "VARCHAR2(5 BYTE)" [not null, default: 'VAT', note: 'Vat/Novat']
  "STATUS" "VARCHAR2(20 BYTE)" [not null, default: 'PENDING', note: '''?????
1.NORMAL (???????????)
2.FINISH (????????????????? SO ?????)
3.CANCEL (????????????????????????????? SO ??? 6 ?????)''']
  "STAFF_ID" NUMBER [not null, note: '?????????????? Quotation']
  "DELIVERY_DETAIL" "VARCHAR2(2000 BYTE)" [note: '???????????????????']
  "PAYMENT_DETAIL" "VARCHAR2(2000 BYTE)" [note: '????????????????????']
  "REMARKS" "VARCHAR2(2000 BYTE)" [note: '????????']
  "MEMO" "VARCHAR2(2000 BYTE)" [note: '??????????????']
  "ACCEPT_PAYMENT" "VARCHAR2(50 BYTE)"
  "ACCEPT_DATE" DATE
  "ACCEPT_STAFF" NUMBER
  "ACCEPT_RECEIVE" "VARCHAR2(20 BYTE)"
  "RECEIVE_DATE" DATE
  "RECEIVE_STAFF" NUMBER
  "CONTACT_POSITION" "VARCHAR2(255 BYTE)"
  "SEND_EMAIL_YN" "CHAR(1 CHAR)" [not null, default: 'N']
  "EMAIL_FINISH_YN" "CHAR(1 CHAR)" [not null, default: 'N']
  "APPROVE_YN" "CHAR(1 CHAR)" [not null, default: 'N']
  "STAFF_SEND_EMAIL" NUMBER
  "APPROVE_DATE" DATE
  "CHK_APPROVE" "CHAR(1 BYTE)" [not null, default: 'N']
  "CHANGE_STOCK_STAFF" NUMBER
  "CHANGE_STOCK_DATE" DATE
  "APPROVE_1_STAFF" NUMBER
  "APPROVE_1_DATE" DATE
  "APPROVE_2_STAFF" NUMBER
  "APPROVE_2_DATE" DATE
  "APPROVE_3_STAFF" NUMBER
  "APPROVE_3_DATE" DATE
  "REV" NUMBER(15,2) [default: 0]
  "REV_F" NUMBER(15,2) [default: 0]

  Checks {
    `"ID" IS NOT NULL` [name: 'SYS_C006080']
    `"CREATE_DATE" IS NOT NULL` [name: 'SYS_C006081']
    `"CREATE_STAFF" IS NOT NULL` [name: 'SYS_C006082']
    `"PO_DATE" IS NOT NULL` [name: 'SYS_C006083']
    `"COMPANY_ID" IS NOT NULL` [name: 'SYS_C006084']
    `"CONTACT_NAME" IS NOT NULL` [name: 'SYS_C006085']
    `"ADDRESS" IS NOT NULL` [name: 'SYS_C006086']
    `"TEL" IS NOT NULL` [name: 'SYS_C006087']
    `"FAX" IS NOT NULL` [name: 'SYS_C006088']
    `"PAYMENT" IS NOT NULL` [name: 'SYS_C006089']
    `"CHECK_VAT" IS NOT NULL` [name: 'SYS_C006090']
    `"STATUS" IS NOT NULL` [name: 'SYS_C006091']
    `"STAFF_ID" IS NOT NULL` [name: 'SYS_C006092']
    `"SEND_EMAIL_YN" IS NOT NULL` [name: 'SYS_C006093']
    `"EMAIL_FINISH_YN" IS NOT NULL` [name: 'SYS_C006094']
    `"APPROVE_YN" IS NOT NULL` [name: 'SYS_C006095']
    `"CHK_APPROVE" IS NOT NULL` [name: 'SYS_C006096']
  }

  Indexes {
    ID [pk, name: "PK_PO"]
    PO_NO [unique, name: "AK_KEY_2_PO"]
    `TO_DATE(TO_CHAR("PO_DATE",'ddmmyyyy'),'ddmmyyyy')` [name: "SIAMCHAI_OP"]
    `TO_DATE(TO_CHAR("PO_DATE",'yyyy-mm-dd'),'yyyy-mm-dd')` [name: "SIAMCHAI_OP"]
  }
}

Table "SIAMCHAI_OP"."PO_DETAIL" {
  "ID" NUMBER [not null]
  "PO_ID" NUMBER [not null, note: '?????? PO ??????????']
  "PRODUCT_ID" NUMBER [not null, note: 'id ?????????']
  "PRODUCT_CODE" "VARCHAR2(255 BYTE)" [not null, note: '??????????']
  "PRODUCT_DESC" "VARCHAR2(1000 BYTE)" [note: '????????????????']
  "BRAND" "VARCHAR2(100 BYTE)" [note: '????????????']
  "QTY" NUMBER [not null, note: '?????']
  "COST" NUMBER(10,2) [note: '??????? (????????? Report)']
  "PRICE" NUMBER [not null, note: '???????']
  "STATUS" "VARCHAR2(8 BYTE)" [not null, note: '''?????
1. NORMAL
2. FREE
3. OPTIONAL''']
  "SO_DETAIL_ID" NUMBER
  "TO_SHOP_ID" NUMBER
  "DELIVERY_DATE" DATE
  "STOCKIN_QTY" NUMBER [default: 0]
  "MIN_PRICE" NUMBER
  "PROMOTION" "VARCHAR2(50 BYTE)"
  "RECOMMENDED_PRICE" NUMBER(10,2)
  "COST_TYPE" "VARCHAR2(10 BYTE)" [default: 'AVERAGE']
  "AVG_PRICE" NUMBER
  "PROJECT" "VARCHAR2(10 CHAR)" [default: '']
  "COST_PRODUCT" NUMBER
  "IAD_COST" NUMBER
  "NOTE" "VARCHAR2(255 BYTE)"
  "CN_ID" NUMBER
  "DATA_FROM" "VARCHAR2(20 BYTE)" [default: 'NORMAL']
  "PR_DETAIL_ID" NUMBER
  "SELL_QTY" NUMBER [not null, default: 0]
  "REMAIN_QTY" NUMBER [not null, default: 0]
  "FLAG" "VARCHAR2(20 BYTE)"
  "STAFF_ACTION" NUMBER
  "DATE_ACTION" TIMESTAMP(3)
  "REASON_APPROVE" "VARCHAR2(100 BYTE)"
  "REASON_CONFIRM" "VARCHAR2(500 BYTE)"
  "PRODUCT_SET" "VARCHAR2(40 BYTE)"
  "STAFF_REQ_APPROVE" NUMBER

  Checks {
    `"SELL_QTY" IS NOT NULL` [name: 'SYS_C00161091']
    `"REMAIN_QTY" IS NOT NULL` [name: 'SYS_C00161092']
    `"ID" IS NOT NULL` [name: 'SYS_C006099']
    `"PO_ID" IS NOT NULL` [name: 'SYS_C006100']
    `"PRODUCT_ID" IS NOT NULL` [name: 'SYS_C006101']
    `"PRODUCT_CODE" IS NOT NULL` [name: 'SYS_C006102']
    `"QTY" IS NOT NULL` [name: 'SYS_C006103']
    `"PRICE" IS NOT NULL` [name: 'SYS_C006104']
    `"STATUS" IS NOT NULL` [name: 'SYS_C006105']
  }

  Indexes {
    ID [pk, name: "PK_PO_DETAIL"]
    PRODUCT_SET [name: "SIAMCHAI_OP"]
    (PR_DETAIL_ID, STOCKIN_QTY) [name: "SIAMCHAI_OP"]
    PO_ID [name: "SIAMCHAI_OP"]
    PRODUCT_ID [name: "SIAMCHAI_OP"]
    PR_DETAIL_ID [name: "SIAMCHAI_OP"]
  }
}


Ref: "SIAMCHAI_OP"."PO_DETAIL"."PO_ID" < "SIAMCHAI_OP"."PO"."ID"

Ref: "SIAMCHAI_OP"."PO_DETAIL"."PRODUCT_ID" < "SIAMCHAI_STOCK"."PU_PRODUCT"."ID"

Ref: "SIAMCHAI_OP"."PO_DETAIL"."TO_SHOP_ID" <? "SIAMCHAI_STOCK"."SHOP"."ID"

Ref: "SIAMCHAI_OP"."PO"."COMPANY_ID" < "SIAMCHAI_STOCK"."COMPANY"."ID"

Ref: "SIAMCHAI_OP"."PO"."STAFF_ID" < "SIAMCHAI_STOCK"."STAFF"."ID"

Ref: "SIAMCHAI_OP"."PO"."APPROVE_1_STAFF" <? "SIAMCHAI_STOCK"."STAFF"."ID"

Ref: "SIAMCHAI_OP"."PO"."APPROVE_2_STAFF" <? "SIAMCHAI_STOCK"."STAFF"."ID"

Ref: "SIAMCHAI_OP"."PO"."APPROVE_3_STAFF" <? "SIAMCHAI_STOCK"."STAFF"."ID"

Ref: "SIAMCHAI_OP"."PO_DETAIL"."STAFF_ACTION" <? "SIAMCHAI_STOCK"."MYSQL_STAFF"."ID"
Table "SIAMCHAI_STOCK"."BS_BALANCE_STOCK" {
  "ID" NUMBER [not null]
  "PU_PRODUCT_ID" NUMBER
  "SHOP_ID" NUMBER
  "CURRENT_QTY" NUMBER
  "TRUESELL_QTY_7_DAY" NUMBER
  "TARGET_QTY_7_DAY_ORIGINAL" NUMBER
  "TARGET_QTY_7_DAY" NUMBER
  "CURRENT_QTY_BY_TYPE" NUMBER
  "TARGET_QTY_BY_TYPE_7_DAY" NUMBER
  "MIN_QTY" NUMBER
  "MAX_QTY" NUMBER
  "PO_QTY" NUMBER
  "TRANS_IN_QTY" NUMBER
  "TRANS_OUT_QTY" NUMBER
  "PO_STATUS" "VARCHAR2(50 CHAR)" [default: 'รอตัดสินใจ']
  "CREATED_AT" DATE [default: `SYSDATE`]
  "TRUESELL_QTY_30_DAY" NUMBER
  "TARGET_QTY_30_DAY_ORIGINAL" NUMBER
  "TARGET_QTY_30_DAY" NUMBER
  "TARGET_QTY_BY_TYPE_30_DAY" NUMBER

  Indexes {
    ID [pk, name: "SYS_C009530"]
  }
}

Ref: "SIAMCHAI_STOCK"."BS_BALANCE_STOCK"."PU_PRODUCT_ID" <>? "SIAMCHAI_STOCK"."PU_PRODUCT"."ID"

Ref: "SIAMCHAI_STOCK"."BS_BALANCE_STOCK"."SHOP_ID" <>? "SIAMCHAI_STOCK"."SHOP"."ID"
Table "SIAMCHAI_STOCK"."BS_PG_SETTING" {
  "ID" NUMBER [not null]
  "SHOP_ID" NUMBER [not null, note: 'สาขา']
  "PRODUCT_GROUP_ID" NUMBER [not null, note: 'กลุ่มสินค้า']
  "MIN_QTY" NUMBER [note: 'จำนวนต่ำสุด']
  "MAX_QTY" NUMBER [note: 'จำนวนสูงสุด']
  "SELL_MULTIPLY" NUMBER [note: 'เลขกำลังยอดขาย']
  "SHOW_QTY" NUMBER [note: 'จำนวนตัวโชว์']
  "CREATED_AT" DATE [not null, default: `SYSDATE`, note: 'สร้างเมื่อ']
  "CREATED_BY" NUMBER [note: 'สร้างโดย']
  "UPDATED_AT" DATE [note: 'อัพเดทเมื่อ']
  "UPDATED_BY" NUMBER [note: 'อัพเดทโดย']
  "CATEGORY_ID" NUMBER [note: 'ประเภทสินค้า']
  "TYPE_ID" NUMBER [note: 'ชนิดสินค้า']
  "BRAND_ID" NUMBER [note: 'ยี่ห้อสินค้า']

  Checks {
    `"ID" IS NOT NULL` [name: 'SYS_C006239']
    `"SHOP_ID" IS NOT NULL` [name: 'SYS_C006240']
    `"PRODUCT_GROUP_ID" IS NOT NULL` [name: 'SYS_C006241']
    `"CREATED_AT" IS NOT NULL` [name: 'SYS_C006242']
  }

  Indexes {
    ID [unique, name: "SYS_C0069112"]
    BRAND_ID [name: "SIAMCHAI_STOCK"]
    PRODUCT_GROUP_ID [name: "SIAMCHAI_STOCK"]
    SHOP_ID [name: "SIAMCHAI_STOCK"]
  }
}

Table "SIAMCHAI_STOCK"."MASTER_PRODUCT_BRAND" {
  "ID" NUMBER [not null]
  "NAME" "VARCHAR2(255 BYTE)"
  "STATUS" "VARCHAR2(10 BYTE)" [not null, default: 'INACTIVE']
  "CREATE_BY" NUMBER
  "CREATE_AT" DATE [not null, default: `sysdate`]
  "MYSQL_ID" NUMBER
  "COMPANY_ID" NUMBER

  Checks {
    `"STATUS" IS NOT NULL` [name: 'SYS_C006410']
    `"CREATE_AT" IS NOT NULL` [name: 'SYS_C006411']
    `"STATUS" IS NOT NULL` [name: 'SYS_C006412']
    `"CREATE_AT" IS NOT NULL` [name: 'SYS_C006413']
  }

  Indexes {
    ID [pk, name: "PK_MP_BRAND"]
    ID [unique, name: "SIAMCHAI_STOCK"]
  }
}

Table "SIAMCHAI_STOCK"."MASTER_PRODUCT_CATEGORY" {
  "ID" NUMBER [not null]
  "NAME" "VARCHAR2(255 BYTE)"
  "STATUS" "VARCHAR2(10 BYTE)" [not null, default: 'INACTIVE']
  "CREATE_BY" NUMBER
  "CREATE_AT" DATE [not null, default: `sysdate`]
  "MYSQL_ID" NUMBER

  Checks {
    `"STATUS" IS NOT NULL` [name: 'SYS_C006415']
    `"CREATE_AT" IS NOT NULL` [name: 'SYS_C006416']
  }

  Indexes {
    ID [pk, name: "IX_CATEGORY_ID"]
  }
}

Table "SIAMCHAI_STOCK"."MASTER_PRODUCT_MODEL" {
  "ID" NUMBER [not null]
  "NAME" "VARCHAR2(255 BYTE)"
  "STATUS" "VARCHAR2(10 BYTE)" [not null, default: 'INACTIVE']
  "CREATE_BY" NUMBER
  "CREATE_AT" DATE [not null, default: `sysdate`]
  "MYSQL_ID" NUMBER

  Checks {
    `"STATUS" IS NOT NULL` [name: 'SYS_C006420']
    `"CREATE_AT" IS NOT NULL` [name: 'SYS_C006421']
    `"STATUS" IS NOT NULL` [name: 'SYS_C006422']
    `"CREATE_AT" IS NOT NULL` [name: 'SYS_C006423']
    `"STATUS" IS NOT NULL` [name: 'SYS_C006424']
    `"CREATE_AT" IS NOT NULL` [name: 'SYS_C006425']
  }

  Indexes {
    ID [pk, name: "PRI_MODEL_ID"]
  }
}

Table "SIAMCHAI_STOCK"."MASTER_PRODUCT_SIZE" {
  "ID" NUMBER [not null]
  "NAME" "VARCHAR2(255 BYTE)"
  "STATUS" "VARCHAR2(10 BYTE)" [not null, default: 'INACTIVE']
  "CREATE_BY" NUMBER
  "CREATE_AT" DATE [not null, default: `sysdate`]
  "MYSQL_ID" NUMBER

  Checks {
    `"STATUS" IS NOT NULL` [name: 'SYS_C006427']
    `"CREATE_AT" IS NOT NULL` [name: 'SYS_C006428']
  }

  Indexes {
    ID [pk, name: "PRI_SIZE_ID"]
  }
}

Table "SIAMCHAI_STOCK"."MASTER_PRODUCT_TYPE" {
  "ID" NUMBER [not null]
  "NAME" "VARCHAR2(255 BYTE)"
  "STATUS" "VARCHAR2(10 BYTE)" [not null, default: 'INACTIVE']
  "CREATE_BY" NUMBER
  "CREATE_AT" DATE [not null, default: `sysdate`]
  "MYSQL_ID" NUMBER

  Checks {
    `"STATUS" IS NOT NULL` [name: 'SYS_C006430']
    `"CREATE_AT" IS NOT NULL` [name: 'SYS_C006431']
  }

  Indexes {
    ID [pk, name: "PRI_TYPE_ID"]
  }
}

Table "SIAMCHAI_STOCK"."MASTER_PRODUCT_UNIT" {
  "ID" NUMBER [not null]
  "NAME" "VARCHAR2(255 BYTE)"
  "STATUS" "VARCHAR2(10 BYTE)" [not null, default: 'INACTIVE']
  "CREATE_BY" NUMBER
  "CREATE_AT" DATE [not null, default: `sysdate`]
  "MYSQL_ID" NUMBER

  Checks {
    `"STATUS" IS NOT NULL` [name: 'SYS_C006433']
    `"CREATE_AT" IS NOT NULL` [name: 'SYS_C006434']
  }

  Indexes {
    ID [pk, name: "PRI_MP_UNIT"]
  }
}

Table "SIAMCHAI_STOCK"."PRODUCT_GROUP" {
  "ID" NUMBER [not null]
  "DESCRIPTION" "VARCHAR2(255 BYTE)"
  "CREATE_BY" NUMBER
  "CREATE_AT" DATE [not null, default: `sysdate`]
  "MYSQL_ID" NUMBER
  "CODE" "VARCHAR2(255 BYTE)"
  "TEXT_TO_SPEAK" "VARCHAR2(255 BYTE)"
  "STATUS" "VARCHAR2(20 CHAR)" [not null, default: 'ACTIVE']

  Checks {
    `"CREATE_AT" IS NOT NULL` [name: 'SYS_C0045688']
    `"ID" IS NOT NULL` [name: 'SYS_C006484']
    `"CREATE_AT" IS NOT NULL` [name: 'SYS_C006485']
    `"STATUS" IS NOT NULL` [name: 'SYS_C006486']
  }

  Indexes {
    ID [pk, name: "SYS_C006488"]
  }
}


Ref: "SIAMCHAI_STOCK"."PRODUCT"."PRODUCT_BRAND_ID" <? "SIAMCHAI_STOCK"."MASTER_PRODUCT_BRAND"."ID"

Ref: "SIAMCHAI_STOCK"."PU_PRODUCT"."PRODUCT_BRAND_ID" <? "SIAMCHAI_STOCK"."MASTER_PRODUCT_BRAND"."ID"

Ref: "SIAMCHAI_STOCK"."PRODUCT"."PRODUCT_MODEL_ID" <? "SIAMCHAI_STOCK"."MASTER_PRODUCT_MODEL"."ID"

Ref: "SIAMCHAI_STOCK"."PRODUCT"."PRODUCT_CATEGORY_ID" <? "SIAMCHAI_STOCK"."MASTER_PRODUCT_CATEGORY"."ID"

Ref: "SIAMCHAI_STOCK"."PRODUCT"."PRODUCT_SIZE_ID" <? "SIAMCHAI_STOCK"."MASTER_PRODUCT_SIZE"."ID"

Ref: "SIAMCHAI_STOCK"."PRODUCT"."PRODUCT_TYPE_ID" <? "SIAMCHAI_STOCK"."MASTER_PRODUCT_TYPE"."ID"

Ref: "SIAMCHAI_STOCK"."PRODUCT"."PRODUCT_UNIT_ID" <? "SIAMCHAI_STOCK"."MASTER_PRODUCT_UNIT"."ID"

Ref: "SIAMCHAI_STOCK"."PRODUCT"."PRODUCT_GROUP_ID" <? "SIAMCHAI_STOCK"."PRODUCT_GROUP"."ID"

Ref: "SIAMCHAI_STOCK"."PRODUCT"."GROUP_ID" <? "SIAMCHAI_STOCK"."PRODUCT_GROUP"."ID"

Ref: "SIAMCHAI_STOCK"."PU_PRODUCT"."PRODUCT_MODEL_ID" <? "SIAMCHAI_STOCK"."MASTER_PRODUCT_MODEL"."ID"

Ref: "SIAMCHAI_STOCK"."PU_PRODUCT"."PRODUCT_CATEGORY_ID" <? "SIAMCHAI_STOCK"."MASTER_PRODUCT_CATEGORY"."ID"

Ref: "SIAMCHAI_STOCK"."PU_PRODUCT"."PRODUCT_SIZE_ID" <? "SIAMCHAI_STOCK"."MASTER_PRODUCT_SIZE"."ID"

Ref: "SIAMCHAI_STOCK"."PU_PRODUCT"."PRODUCT_TYPE_ID" <? "SIAMCHAI_STOCK"."MASTER_PRODUCT_TYPE"."ID"

Ref: "SIAMCHAI_STOCK"."PU_PRODUCT"."GROUP_ID" <? "SIAMCHAI_STOCK"."PRODUCT_GROUP"."ID"